# Generated by Django 3.2.8 on 2023-04-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0016_auto_20230406_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Delay', 'Delay'), ('Offline', 'Offline'), ('NAT', 'NAT'), ('Disabled', 'Disabled')], default='NAT', max_length=10),
        ),
    ]
